### ISSUE TITLE
Make geographies flexible

### ISSUE THREAD

**Issue by bstabler** [RSGInc/populationsim#13]
We need to support N-number of lower level geographies.  For example, in the settings file we have:
```
geographies: [REGION, PUMA, TRACT, TAZ]
seed_geography: PUMA

#or

geographies: [REGION, PUMA, TRACT, TAZ, MAZ]
seed_geography: PUMA
```

There can only be one geography in the `geographies` list before the `seed_geography` and the geographies after the `seed_geography` geography are lower level.  There can be as many lower level geographies as the user wants.

**Comment by toliwaga** [comment]
Currently the code is hard-wired to know that there are two levels of geography below seed, and there are two dedicated processors for balancing those sub_levels. 

We can make geographies flexible by specifying them in settings:
```
geographies: [REGION, PUMA, TRACT, TAZ]
seed_geography: PUMA
```
Automating the process of iterating down through the tree of sub-geographies should not be difficult, but it might be nice to retain the current feature that each level of sub-geography is handled as a separate step, with data pipeline checkpointing and restartability.

You could imagine moving the _MODELS list to the settings file (which might make sense architecturally for asim generally) and/or introducing a notion of sub-steps to be iterated through either inside or outside the checkpointing. 

Interestingly, orca has a similar, but inverted, concept of step iteration built in, but which doesn't play well with out pipelining architecture. In orca, the entire list of steps is iterated over each iter_var. 

We want it the other way round. Something like:
```
models:
- input_pre_processor
- setup_data_structures
- initial_seed_balancing
- meta_control_factoring
- final_seed_balancing
- integerize_final_seed_weights
- {step_name: sub_balancing, iter_vars: [TRACT, TAZ]}
- sub_balancing.TAZ
- expand_population
- summarize
- write_results
```
(Though we might want to use anchors in the settings file to avoid redundancy.)

**Comment by bstabler** [comment]
We decided to add to the pipeliner the ability to read an optional dictionary of arguments for each step.  This has lots of uses and means the pipeline acts more like DOS or Bash as well.  So, for the example above, the model list will look something like:

```
models:
- input_pre_processor
- setup_data_structures
- initial_seed_balancing
- meta_control_factoring
- final_seed_balancing
- integerize_final_seed_weights
- sub_balancing, GEOG=TRACT
- sub_balancing, GEOG=TAZ
- expand_population
- summarize
- write_results
```
