### ISSUE TITLE
Add update geography feature

### ISSUE THREAD

**Issue by bstabler** [RSGInc/populationsim#14]
Here's the initial design from @jfdman 

As far as the single geography feature, here is what I propose to do. The user would specify the controls for a subset of geographies – usually just a few zones, along with a pre-created synthetic population. The controls would have to be specified for the lowest level geographies that the previous synthetic population was created for – the reason is obvious, if you don’t specify the lowest geography of the existing population you can’t use the output in the model. The controls do not have to be consistent with the controls used to generate the original synthetic population. For example, you could use some combination of housing type and number of bathrooms per unit as a control even if neither was used as a control in the original population. There would only be single-level controls – global controls cannot be specified since there is no guarantee that the selected geographies add up to a global geography, and because this simply isn’t a requirement of the use case. The user would also have the ability to specify whether to over-write the existing population in the selected geographies or add to the existing population.

Once the tool is set up, it would read in the existing population. It would synthesize the households in the specified geographies by first weighting the PUMS data to match the controls, then sequentially integerizing the weights for each geography. Simultaneous integerization isn’t necessary since there are no global controls. The households\persons in the existing population outside the selected area would be unaffected. The output file would contain the population for the entire region, with the synthetic population in the selected geography either replacing the existing population in that geography or adding to it.

**Comment by toliwaga** [comment]
Does "weighting the PUMS data to match the controls" mean aggregating the lowest level geography controls to seed level and balancing, and then using that balanced weight (integerized?) as the 'seed weight' for sequential balancing individual low level geographies?
