### ISSUE TITLE
check code against SOABM populationsim data

### ISSUE THREAD

**Issue by toliwaga** [RSGInc/populationsim#15]
assert failing in do_integerizing for backstopped controls for TAZ 141 seed 900
assert len(incidence_table.index) > 1

**Comment by bstabler** [comment]
was this done?

**Comment by bettinardi** [comment]
I thought Binny was building an instruction set around a working copy for the SOABM?

**Comment by bstabler** [comment]
@binnympaul will test this during the user guide development process

**Comment by bstabler** [comment]
#53 is required to run the SOABM example
