### ISSUE TITLE
Missing Module in ActivitySim PyPi Dependency

### ISSUE THREAD

**Issue by danielsclint** [RSGInc/populationsim#21]
The setup depends on the RSGInc ActivitySim fork that includes an 'inject' module in activitysim.core. This module does not exist in the pypi version of ActivitySim.

https://github.com/RSGInc/populationsim/blob/02cd75fdb5c991fd58c5bcb0271020852d452a6d/populationsim/steps/input_pre_processor.py#L10

**Comment by bstabler** [comment]
It will soon.  It is in the atwork-subtours branch, but hasn't yet been officially released since we haven't completed the testing and documentation.

**Comment by bstabler** [comment]
Updated - https://pypi.python.org/pypi/activitysim
