### ISSUE TITLE
ortools integerization results varies from platform to platform

### ISSUE THREAD

**Issue by toliwaga** [RSGInc/populationsim#23]
Regression tests unreliable since edge case results depend on exact ortools/cbc version

**Comment by bstabler** [comment]
@binnympaul - make a note in the documentation about this and then close the issue.

**Comment by bettinardi** [comment]
I disagree - the ABM code doesn't care about this.
This is pocessing that needs to occur on the pop gen side - not the ABM side

**Comment by bstabler** [comment]
I think you meant to comment on https://github.com/RSGInc/populationsim/issues/16
