### ISSUE TITLE
User should not be required to specify expanded outputs in the output_tables: setting

### ISSUE THREAD

**Issue by binnympaul** [RSGInc/populationsim#34]
The user should not be required to explicitly specify the expanded_households or expanded_persons file in the output_table settings in the settings.YAML file. These should be written out regardless.

**Comment by toliwaga** [comment]
I am not sure I understand why this wold be a good thing.

**Comment by binnympaul** [comment]
All the summary files need not be specified in the settings file, I thought expanded outputs is also something that the user would always want to see?

**Comment by toliwaga** [comment]
It might depend on how they are using the data, but probably usually they would want that.  We just might not want to make it hard/impossible to turn off.

As far as the summary files go, the user maybe should be able to control which of them are printed out, too... 

But sure, we can do this if you think it is the right thing.

**Comment by binnympaul** [comment]
Yes, I think you are right - nothing wrong in having that flexibility to choose , the default settings in the example setups would be to write out expanded outputs.

I was running example setups, with following settings:
output_tables:
  action: include
  tables:
    - households
    - persons
    - expanded_household_ids

It printed all the summary files along with the ones listed here. Could you please confirm if this option works on summary files.

**Comment by toliwaga** [comment]
It doesn't work on summary files - I was just saying maybe it should.
I wasn't really sure we wanted (all anyway) the summary files or if they were mostly for debugging during development, but I guess we do?..

**Comment by binnympaul** [comment]
I have tried to describe all of them in the user guide. If we have the option to turn them off, we can leave them as is.
