### ISSUE TITLE
Better Error Messaging

### ISSUE THREAD

**Issue by bettinardi** [RSGInc/populationsim#61]
I think one piece of low fruit in regards to error messaging, would be better reporting on which zone is being worked on at the time of the failure.  This could either be handled, by more consistently writing to the screen which step and which zone is being worked on for every zone/step, or by building better error messaging that could report which step and with which zone the process died in.

**Comment by bstabler** [comment]
With the appropriate conda environment activated (i.e. `activate popsim`), you can install the master branch version of the package directly from GitHub with:

`pip install --upgrade https://github.com/RSGInc/populationsim/zipball/master`
