### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by bstabler** [RSGInc/populationsim#69]
Need to make sure PopulationSim works for Python 3 (and update all related materials as well).  Updating ActivitySim to work for both 2 and 3 wasn't a big deal, so updating PopulationSim should be relatively straightforward.

**Comment by toliwaga** [comment]
pytest version 4.2.0 now issues the following warning:
```You are using Python 2.7.15, which will no longer be supported in pytest 5.0```
