### ISSUE TITLE
example_calm needs a little explanation

### ISSUE THREAD

**Issue by dkyleward** [RSGInc/populationsim#85]
I'm running a test of the data located here:
https://github.com/RSGInc/populationsim/tree/master/example_calm/data

I've had to guess at a lot of the field names/meanings. Here are the minimum things that I need to know that I can't make up:

1. Neither the household nor person seed has as a TAZ or Tract column (that I can see). I need that to match to the TAZ and tract controls. I don't see how to make use of the geo equivalency file, either.
2. I can't determine which seed field gives me the number of household workers. On the off chance that it's the "COW" (for "class of worker"?), then I need to know which categorical values translate to worker before I can summarize by household. To be clear, the tract level controls apply controls by the number of workers in the household, so that's what I'm trying to determine.

Other stuff I made up like the income group and age group ranges. The actual ranges would be nice to have, but are not required. I've also assumed that "NP" in the household table is "number of persons" (or household size).

Thanks!

**Comment by sarahcmap** [comment]
Happened to be looking at issues and wanted to see if I could help.  

A lot of the field names come from the PUMS data file, which appears to be from 2006-2010.  A look at the data dictionary will help out: https://www2.census.gov/programs-surveys/acs/tech_docs/pums/data_dict/PUMS_Data_Dictionary_2006-2010.pdf 
You'll see that NP is indeed number of persons.  

1.  The seed files are at the PUMA geography level, and the population synthesis process is what places each household into a TAZ.  After the process is complete, you can see how your synthetic population compares to the controls by looking at the output tables that are specified in the setting.yaml file.  The geo_cross_walk.csv is just what tells the program how the different geographies are connected to each other.   

2.  You refer to the tract level controls on the number of workers.  In the controls file, see that the "expression" field for the hh worker controls is households.NWESR, and the statements suggest that this NWESR variable is the number of workers in the household.  This appears to be a calculated field based on the ESR variable in the person file.

**Comment by bettinardi** [comment]
I could also add, as an ODOT employee that provided the "CALM" example.  If you look under the "config" folder in the "controls.csv" you will see programmed definitions for relevant fields like the Age and Income categories.

**Comment by dkyleward** [comment]
Thank you both!
